# Generated by Django 3.1.6 on 2021-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20210208_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_food',
            name='food_image',
            field=models.CharField(default='https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg?compress=1&resize=400x300', max_length=1000),
        ),
    ]
